### ISSUE TITLE
Why not display?

### ISSUE THREAD

**Issue by Wilson403** [Aviortheking/codestats-readme#22]
It is normal last month, but now not display
![image](https://user-images.githubusercontent.com/38308449/206352639-cb123b6e-9b40-4f4b-9264-cb3c2b50ad21.png)
![image](https://user-images.githubusercontent.com/38308449/206352654-e3963174-2d1f-41ae-9de8-e0749f395815.png)
![image](https://user-images.githubusercontent.com/38308449/206353101-bd602642-d28f-471c-a5df-1f46aaceae11.png)

**Comment by domai-tb** [comment]
The Vercel App seems to be down and the code is also not working anymore by default (That's the reason why all images shown the profile card in the readme). I did a bit of workarounds in my [Fork](https://github.com/domai-tb/codestats-readme) to address this issues. It can be used like intended, just adjust the API endpoints `/profile` (instead of `/api`), `/history` (instead of `/api/history`) and `/toplang` (instead of `/api/top-langs`). 

Cheers, :Domai

**Comment by Aviortheking** [comment]
I was kinda banned from Vercel free for having too many requests, So I moved to being on a self host (tho the commit that removed the vercel dep [3938dc9](https://github.com/Aviortheking/codestats-readme/commit/3938dc98fcc51855fb37b675f20d1d226e0e321c)) you just need to change from `https://codestats-readme.vercel.app` to `https://codestats-readme.avior.me`
